services:
  censudex-orders:
    image: ${DOCKER_REGISTRY-}censudex-orders
    build:
      context: .
  orders-db:
    image: mysql:9.4.0

  rabbitmq:
    image: rabbitmq:4.2.0-management-alpine

volumes:
  rabbitmq_data:
    driver: local
  rabbitmq_logs:
    driver: local
  mysql_data:
    driver: local

networks:
  censudex-network:
    driver: bridge
